"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Aakanksha Mahajan and <FULL NAME>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: am96292
UT EID 2:
"""

from abc import ABC, abstractmethod
import random

DAILY_EXPENSE = 60
HAPPINESS_THRESHOLD = 50
MANAGER_BONUS = 1000
TEMP_EMPLOYEE_PERFORMANCE_THRESHOLD = 50
PERM_EMPLOYEE_PERFORMANCE_THRESHOLD = 25
RELATIONSHIP_THRESHOLD = 10
INITIAL_PERFORMANCE = 75
INITIAL_HAPPINESS = 50
PERCENTAGE_MAX = 100
PERCENTAGE_MIN = 0
SALARY_ERROR_MESSAGE = "Salary must be non-negative."


# TODO: implement this class. You may delete this comment when you are done.
class Employee(ABC):
    """
    Abstract base class representing a generic employee in the system.
    """

    def __init__(self, name, manager, salary, savings):
        self.relationships = {}
        self.savings = savings
        self.is_employed = True
        self.__name = name
        self.__manager = manager
        self.performance = INITIAL_PERFORMANCE
        self.happiness = INITIAL_HAPPINESS
        self._salary = salary
    
    @property
    def name(self):
        return self.__name
    
    @property
    def manager(self):
        return self.__manager
    
    @property
    def performance(self):
        return self.performance
    
    @performance.setter
    def performance(self, value):
        if value > PERCENTAGE_MIN and value < PERCENTAGE_MAX:
            self.performance = value
        elif value > PERCENTAGE_MAX:
            self.performance = PERCENTAGE_MAX
        elif value < PERCENTAGE_MIN:
            self.performance = PERCENTAGE_MIN

    @property
    def happiness(self):
        return self.happiness
    
    @happiness.setter
    def happiness(self, value):
        if value > PERCENTAGE_MIN and value < PERCENTAGE_MAX:
            self.happiness = value
        elif value > PERCENTAGE_MAX:
            self.happiness = PERCENTAGE_MAX
        elif value < PERCENTAGE_MIN:
            self.happiness = PERCENTAGE_MIN
    
    @property
    def salary(self):
        return self._salary
    
    @salary.setter
    def salary(self, value):
        if value < 0:
            raise ValueError("SALARY_ERROR_MESSAGE")
        else:
            self._salary = value
    
    @abstractmethod
    def work(self):
        pass

    def interact(self, other):
        if other.name not in self.relationships:
            self.relationships[other.name] = 0
        if self.relationships[other.name] > RELATIONSHIP_THRESHOLD:
            self.happiness += 1
        elif self.happiness >= HAPPINESS_THRESHOLD and other.happiness >= HAPPINESS_THRESHOLD:
            self.relationships[other.name] += 1
        else:
            self.relationships[other.name] -= 1
            self.happiness -= 1

# TODO: implement this class. You may delete this comment when you are done.
class Manager(Employee):
    """
    A subclass of Employee representing a manager.
    """


# TODO: implement this class. You may delete this comment when you are done.
class TemporaryEmployee(Employee):
    """
    A subclass of Employee representing a temporary employee.
    """


# TODO: implement this class. You may delete this comment when you are done.
class PermanentEmployee(Employee):
    """
    A subclass of Employee representing a permanent employee.
    """
